// Vocabulary data used by vocab.html and practice.html.
// Edit this file when you want to add, remove, or update vocabulary terms.
window.VOCAB_DATA = [
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Marketing",
    "definition": "The process by which companies engage customers, build strong customer relationships, and create customer value in order to capture value from customers in return.",
    "example": "Marketing is not just advertising — it starts with understanding what the customer actually needs.",
    "blanked": "[[BLANK]] is not just advertising — it starts with understanding what the customer actually needs.",
    "blank_answer": "Marketing",
    "matched_text": "Marketing",
    "vi": "Tiếp thị / Marketing"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Need",
    "definition": "A state of felt deprivation.",
    "example": "Her thesis starts from a real need: the company doesn't fully understand its customers yet.",
    "blanked": "Her thesis starts from a real [[BLANK]]: the company doesn't fully understand its customers yet.",
    "blank_answer": "need",
    "matched_text": "need",
    "vi": "Nhu cầu"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Want",
    "definition": "The form human needs take as they are shaped by culture and individual personality.",
    "example": "Everyone needs to eat, but a want is choosing a specific brand of coffee.",
    "blanked": "Everyone needs to eat, but a [[BLANK]] is choosing a specific brand of coffee.",
    "blank_answer": "want",
    "matched_text": "want",
    "vi": "Mong muốn"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Demand",
    "definition": "Human wants that are backed by buying power.",
    "example": "Many customers want the product, but only some represent real demand because they can afford it.",
    "blanked": "Many customers want the product, but only some represent real [[BLANK]] because they can afford it.",
    "blank_answer": "demand",
    "matched_text": "demand",
    "vi": "Nhu cầu có khả năng chi trả"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Exchange",
    "definition": "The act of obtaining a desired object from someone by offering something in return.",
    "example": "A sale is just one kind of exchange — the customer gives money, the company gives value.",
    "blanked": "A sale is just one kind of [[BLANK]] — the customer gives money, the company gives value.",
    "blank_answer": "exchange",
    "matched_text": "exchange",
    "vi": "Trao đổi"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Market",
    "definition": "The set of all actual and potential buyers of a product or service.",
    "example": "Before targeting anyone, you first have to define the market you're even looking at.",
    "blanked": "Before targeting anyone, you first have to define the [[BLANK]] you're even looking at.",
    "blank_answer": "market",
    "matched_text": "market",
    "vi": "Thị trường"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Customer value",
    "definition": "The customer's evaluation of the difference between all the benefits and all the costs of a market offer relative to competing offers.",
    "example": "If two products cost the same, the one offering more customer value usually wins.",
    "blanked": "If two products cost the same, the one offering more [[BLANK]] usually wins.",
    "blank_answer": "customer value",
    "matched_text": "customer value",
    "vi": "Giá trị khách hàng"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Customer satisfaction",
    "definition": "The extent to which a product's perceived performance matches a buyer's expectations.",
    "example": "Customer satisfaction drops fast when the product undersells its own marketing claims.",
    "blanked": "[[BLANK]] drops fast when the product undersells its own marketing claims.",
    "blank_answer": "Customer satisfaction",
    "matched_text": "Customer satisfaction",
    "vi": "Sự hài lòng của khách hàng"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Marketing mix",
    "definition": "The set of tactical marketing tools — product, price, place, and promotion — that the firm blends to produce the response it wants in the target market.",
    "example": "Chapter 3 of her thesis will need a full marketing mix, not just a list of products.",
    "blanked": "Chapter 3 of her thesis will need a full [[BLANK]], not just a list of products.",
    "blank_answer": "marketing mix",
    "matched_text": "marketing mix",
    "vi": "Marketing hỗn hợp"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Marketing myopia",
    "definition": "The mistake of paying more attention to the specific products a company offers than to the benefits and experiences produced by these products.",
    "example": "Focusing only on the product instead of the customer's real problem is a classic case of marketing myopia.",
    "blanked": "Focusing only on the product instead of the customer's real problem is a classic case of [[BLANK]].",
    "blank_answer": "marketing myopia",
    "matched_text": "marketing myopia",
    "vi": "Cận thị marketing"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Customer relationship management (CRM)",
    "definition": "The overall process of building and maintaining profitable customer relationships by delivering superior customer value and satisfaction.",
    "example": "Good CRM means the company still remembers you after the first purchase.",
    "blanked": "Good [[BLANK]] means the company still remembers you after the first purchase.",
    "blank_answer": "CRM",
    "matched_text": "CRM",
    "vi": "Quản trị quan hệ khách hàng"
  },
  {
    "week": 1,
    "topic": "Marketing Foundations",
    "term": "Customer lifetime value",
    "definition": "The value of the entire stream of purchases a customer makes over a lifetime of patronage.",
    "example": "One loyal customer's lifetime value can be worth more than ten one-time buyers.",
    "blanked": "One loyal customer's [[BLANK]] can be worth more than ten one-time buyers.",
    "blank_answer": "lifetime value",
    "matched_text": "lifetime value",
    "vi": "Giá trị vòng đời khách hàng"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "Mission statement",
    "definition": "A statement of the organization's purpose — what it wants to accomplish in the larger environment.",
    "example": "Every section of her Chapter 1 should connect back to the company's mission statement.",
    "blanked": "Every section of her Chapter 1 should connect back to the company's [[BLANK]].",
    "blank_answer": "mission statement",
    "matched_text": "mission statement",
    "vi": "Tuyên bố sứ mệnh"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "Growth-share matrix",
    "definition": "A portfolio-planning method that evaluates a company's SBUs in terms of market growth rate and relative market share.",
    "example": "The growth-share matrix (BCG matrix) helps decide which products to invest in and which to drop.",
    "blanked": "The [[BLANK]] (BCG matrix) helps decide which products to invest in and which to drop.",
    "blank_answer": "growth-share matrix",
    "matched_text": "growth-share matrix",
    "vi": "Ma trận tăng trưởng - thị phần"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "Market penetration",
    "definition": "Company growth by increasing sales of current products to current market segments without changing the product.",
    "example": "Selling more of the same product to existing customers is market penetration, not innovation.",
    "blanked": "Selling more of the same product to existing customers is [[BLANK]], not innovation.",
    "blank_answer": "market penetration",
    "matched_text": "market penetration",
    "vi": "Thâm nhập thị trường"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "Diversification",
    "definition": "Company growth through starting up or acquiring businesses outside the company's current products and markets.",
    "example": "Diversification is risky because the company is entering territory it doesn't fully understand yet.",
    "blanked": "[[BLANK]] is risky because the company is entering territory it doesn't fully understand yet.",
    "blank_answer": "Diversification",
    "matched_text": "Diversification",
    "vi": "Đa dạng hóa"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "Marketing strategy",
    "definition": "The marketing logic by which the company hopes to create customer value and achieve profitable customer relationships.",
    "example": "A clear marketing strategy should come before any tactics like ads or promotions.",
    "blanked": "A clear [[BLANK]] should come before any tactics like ads or promotions.",
    "blank_answer": "marketing strategy",
    "matched_text": "marketing strategy",
    "vi": "Chiến lược marketing"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "Marketing implementation",
    "definition": "Turning marketing strategies and plans into marketing actions to accomplish strategic marketing objectives.",
    "example": "A great strategy on paper is worthless without solid marketing implementation.",
    "blanked": "A great strategy on paper is worthless without solid [[BLANK]].",
    "blank_answer": "marketing implementation",
    "matched_text": "marketing implementation",
    "vi": "Triển khai marketing"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "Marketing return on investment (marketing ROI)",
    "definition": "The net return from a marketing investment divided by the costs of the marketing investment.",
    "example": "Her finance chapter should show the expected marketing ROI of the 12-month plan.",
    "blanked": "Her finance chapter should show the expected [[BLANK]] of the 12-month plan.",
    "blank_answer": "marketing ROI",
    "matched_text": "marketing ROI",
    "vi": "Tỷ suất hoàn vốn marketing"
  },
  {
    "week": 2,
    "topic": "Strategic Planning & Company Marketing Strategy",
    "term": "SWOT analysis",
    "definition": "An overall evaluation of the company's strengths (S), weaknesses (W), opportunities (O), and threats (T).",
    "example": "A SWOT analysis is a natural starting point for her Chapter 1 internal analysis.",
    "blanked": "A [[BLANK]] is a natural starting point for her Chapter 1 internal analysis.",
    "blank_answer": "SWOT analysis",
    "matched_text": "SWOT analysis",
    "vi": "Phân tích SWOT"
  },
  {
    "week": 3,
    "topic": "The Marketing Environment",
    "term": "Marketing environment",
    "definition": "The actors and forces outside marketing that affect marketing management's ability to build and maintain successful relationships with target customers.",
    "example": "Even a great strategy can fail if the marketing environment shifts suddenly.",
    "blanked": "Even a great strategy can fail if the [[BLANK]] shifts suddenly.",
    "blank_answer": "marketing environment",
    "matched_text": "marketing environment",
    "vi": "Môi trường marketing"
  },
  {
    "week": 3,
    "topic": "The Marketing Environment",
    "term": "Microenvironment",
    "definition": "The actors close to the company that affect its ability to serve its customers — the company, suppliers, marketing intermediaries, customer markets, competitors, and publics.",
    "example": "Suppliers and competitors are both part of the microenvironment.",
    "blanked": "Suppliers and competitors are both part of the [[BLANK]].",
    "blank_answer": "microenvironment",
    "matched_text": "microenvironment",
    "vi": "Môi trường vi mô"
  },
  {
    "week": 3,
    "topic": "The Marketing Environment",
    "term": "Macroenvironment",
    "definition": "The larger societal forces that affect the microenvironment — demographic, economic, natural, technological, political, and cultural forces.",
    "example": "A new government regulation is a macroenvironment factor outside any single company's control.",
    "blanked": "A new government regulation is a [[BLANK]] factor outside any single company's control.",
    "blank_answer": "macroenvironment",
    "matched_text": "macroenvironment",
    "vi": "Môi trường vĩ mô"
  },
  {
    "week": 3,
    "topic": "The Marketing Environment",
    "term": "Economic environment",
    "definition": "Economic factors that affect consumer purchasing power and spending patterns.",
    "example": "Rising inflation is part of the economic environment, and it directly affects buying power.",
    "blanked": "Rising inflation is part of the [[BLANK]], and it directly affects buying power.",
    "blank_answer": "economic environment",
    "matched_text": "economic environment",
    "vi": "Môi trường kinh tế"
  },
  {
    "week": 3,
    "topic": "The Marketing Environment",
    "term": "Demography",
    "definition": "The study of human populations in terms of size, density, location, age, gender, race, occupation, and other statistics.",
    "example": "Demography tells you who your customers are; it doesn't yet tell you what they want.",
    "blanked": "[[BLANK]] tells you who your customers are; it doesn't yet tell you what they want.",
    "blank_answer": "Demography",
    "matched_text": "Demography",
    "vi": "Nhân khẩu học"
  },
  {
    "week": 3,
    "topic": "The Marketing Environment",
    "term": "Cultural environment",
    "definition": "Institutions and other forces that affect society's basic values, perceptions, preferences, and behaviors.",
    "example": "What counts as a 'gift-worthy' product depends heavily on the cultural environment.",
    "blanked": "What counts as a 'gift-worthy' product depends heavily on the [[BLANK]].",
    "blank_answer": "cultural environment",
    "matched_text": "cultural environment",
    "vi": "Môi trường văn hóa"
  },
  {
    "week": 3,
    "topic": "The Marketing Environment",
    "term": "Competitive marketing intelligence",
    "definition": "The systematic monitoring, collection, and analysis of publicly available information about consumers, competitors, and developments in the marketing environment.",
    "example": "Before naming her competitors, she should gather solid competitive marketing intelligence, not just guesses.",
    "blanked": "Before naming her competitors, she should gather solid [[BLANK]], not just guesses.",
    "blank_answer": "competitive marketing intelligence",
    "matched_text": "competitive marketing intelligence",
    "vi": "Thông tin cạnh tranh marketing"
  },
  {
    "week": 4,
    "topic": "Market Research & Consumer Insights",
    "term": "Marketing information system (MIS)",
    "definition": "People and procedures dedicated to assessing information needs, developing the needed information, and helping decision makers to use the information to generate and validate actionable customer and market insights.",
    "example": "A good MIS turns raw data into decisions, not just reports.",
    "blanked": "A good [[BLANK]] turns raw data into decisions, not just reports.",
    "blank_answer": "MIS",
    "matched_text": "MIS",
    "vi": "Hệ thống thông tin marketing"
  },
  {
    "week": 4,
    "topic": "Market Research & Consumer Insights",
    "term": "Customer insights",
    "definition": "Fresh marketing information-based understandings of customers and the marketplace that become the basis for creating customer value, engagement, and relationships.",
    "example": "The whole point of her market research chapter is to generate real customer insights, not just numbers.",
    "blanked": "The whole point of her market research chapter is to generate real [[BLANK]], not just numbers.",
    "blank_answer": "customer insights",
    "matched_text": "customer insights",
    "vi": "Thấu hiểu khách hàng"
  },
  {
    "week": 4,
    "topic": "Market Research & Consumer Insights",
    "term": "Descriptive research",
    "definition": "Marketing research to better describe marketing problems, situations, or markets, such as the market potential for a product or the demographics and attitudes of consumers.",
    "example": "Descriptive research answers 'what is happening,' not 'why.'",
    "blanked": "[[BLANK]] answers 'what is happening,' not 'why.'",
    "blank_answer": "Descriptive research",
    "matched_text": "Descriptive research",
    "vi": "Nghiên cứu mô tả"
  },
  {
    "week": 4,
    "topic": "Market Research & Consumer Insights",
    "term": "Causal research",
    "definition": "Marketing research to test hypotheses about cause-and-effect relationships.",
    "example": "If she wants to prove a promotion caused higher sales, that's causal research.",
    "blanked": "If she wants to prove a promotion caused higher sales, that's [[BLANK]].",
    "blank_answer": "causal research",
    "matched_text": "causal research",
    "vi": "Nghiên cứu nhân quả"
  },
  {
    "week": 4,
    "topic": "Market Research & Consumer Insights",
    "term": "Exploratory research",
    "definition": "Marketing research to gather preliminary information that will help define problems and suggest hypotheses.",
    "example": "Exploratory research usually comes first, before you know exactly what to measure.",
    "blanked": "[[BLANK]] usually comes first, before you know exactly what to measure.",
    "blank_answer": "Exploratory research",
    "matched_text": "Exploratory research",
    "vi": "Nghiên cứu khám phá"
  },
  {
    "week": 4,
    "topic": "Market Research & Consumer Insights",
    "term": "Survey research",
    "definition": "Gathering primary data by asking people questions about their knowledge, attitudes, preferences, and buying behavior.",
    "example": "Survey research is probably the fastest way for her to gather primary consumer data.",
    "blanked": "[[BLANK]] is probably the fastest way for her to gather primary consumer data.",
    "blank_answer": "Survey research",
    "matched_text": "Survey research",
    "vi": "Nghiên cứu khảo sát"
  },
  {
    "week": 4,
    "topic": "Market Research & Consumer Insights",
    "term": "Ethnographic research",
    "definition": "A form of observational research that involves sending trained observers to watch and interact with consumers in their 'natural environments.'",
    "example": "Watching customers shop in a real store is ethnographic research, not a survey.",
    "blanked": "Watching customers shop in a real store is [[BLANK]], not a survey.",
    "blank_answer": "ethnographic research",
    "matched_text": "ethnographic research",
    "vi": "Nghiên cứu quan sát thực địa"
  },
  {
    "week": 5,
    "topic": "Consumer Behavior",
    "term": "Consumer buyer behavior",
    "definition": "The buying behavior of final consumers — individuals and households that buy goods and services for personal consumption.",
    "example": "Understanding consumer buyer behavior is the foundation of her whole Chapter 2.",
    "blanked": "Understanding [[BLANK]] is the foundation of her whole Chapter 2.",
    "blank_answer": "consumer buyer behavior",
    "matched_text": "consumer buyer behavior",
    "vi": "Hành vi mua của người tiêu dùng"
  },
  {
    "week": 5,
    "topic": "Consumer Behavior",
    "term": "Need recognition",
    "definition": "The first stage of the buyer decision process, in which the consumer recognizes a problem or need.",
    "example": "Marketing can trigger need recognition even before the customer realizes they want something.",
    "blanked": "Marketing can trigger [[BLANK]] even before the customer realizes they want something.",
    "blank_answer": "need recognition",
    "matched_text": "need recognition",
    "vi": "Nhận diện nhu cầu"
  },
  {
    "week": 5,
    "topic": "Consumer Behavior",
    "term": "Cognitive dissonance",
    "definition": "Buyer discomfort caused by postpurchase conflict.",
    "example": "After a big purchase, cognitive dissonance is that nagging feeling of 'did I make the right choice?'",
    "blanked": "After a big purchase, [[BLANK]] is that nagging feeling of 'did I make the right choice?'",
    "blank_answer": "cognitive dissonance",
    "matched_text": "cognitive dissonance",
    "vi": "Bất hòa nhận thức"
  },
  {
    "week": 5,
    "topic": "Consumer Behavior",
    "term": "Adoption process",
    "definition": "The mental process through which an individual passes from first hearing about an innovation to final adoption.",
    "example": "Not everyone goes through the adoption process at the same speed — some are early adopters.",
    "blanked": "Not everyone goes through the [[BLANK]] at the same speed — some are early adopters.",
    "blank_answer": "adoption process",
    "matched_text": "adoption process",
    "vi": "Quá trình chấp nhận sản phẩm mới"
  },
  {
    "week": 5,
    "topic": "Consumer Behavior",
    "term": "Belief",
    "definition": "A descriptive thought that a person holds about something.",
    "example": "If customers hold the belief that a brand is 'cheap-looking,' that belief is hard to change with ads alone.",
    "blanked": "If customers hold the [[BLANK]] that a brand is 'cheap-looking,' that belief is hard to change with ads alone.",
    "blank_answer": "belief",
    "matched_text": "belief",
    "vi": "Niềm tin"
  },
  {
    "week": 5,
    "topic": "Consumer Behavior",
    "term": "Buyer-readiness stages",
    "definition": "The stages consumers normally pass through on their way to a purchase: awareness, knowledge, liking, preference, conviction, and, finally, the actual purchase.",
    "example": "A customer at the 'awareness' stage needs very different messaging than one at 'conviction.'",
    "blanked": "In the [[BLANK]], a customer at the 'awareness' stage needs very different messaging than one at 'conviction.'",
    "blank_answer": "Buyer-readiness stages",
    "matched_text": "Buyer-readiness stages",
    "vi": "Các giai đoạn sẵn sàng mua"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Market segmentation",
    "definition": "Dividing a market into distinct groups of buyers who have different needs, characteristics, or behaviors and who might require separate marketing strategies or mixes.",
    "example": "Without market segmentation, you end up trying to please everyone and satisfying no one.",
    "blanked": "Without [[BLANK]], you end up trying to please everyone and satisfying no one.",
    "blank_answer": "market segmentation",
    "matched_text": "market segmentation",
    "vi": "Phân khúc thị trường"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Demographic segmentation",
    "definition": "Dividing the market into segments based on variables such as age, life-cycle stage, gender, income, occupation, education, religion, ethnicity, and generation.",
    "example": "Demographic segmentation is the easiest to measure, but it doesn't explain why people buy.",
    "blanked": "[[BLANK]] is the easiest to measure, but it doesn't explain why people buy.",
    "blank_answer": "Demographic segmentation",
    "matched_text": "Demographic segmentation",
    "vi": "Phân khúc theo nhân khẩu học"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Psychographic segmentation",
    "definition": "Dividing a market into different segments based on lifestyle or personality characteristics.",
    "example": "Two customers with the same income can land in different segments once you add psychographic segmentation.",
    "blanked": "Two customers with the same income can land in different segments once you add [[BLANK]].",
    "blank_answer": "psychographic segmentation",
    "matched_text": "psychographic segmentation",
    "vi": "Phân khúc theo tâm lý học"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Behavioral segmentation",
    "definition": "Dividing a market into segments based on consumer knowledge, attitudes, uses of a product, or responses to a product.",
    "example": "Behavioral segmentation looks at what people actually do, not just who they are.",
    "blanked": "[[BLANK]] looks at what people actually do, not just who they are.",
    "blank_answer": "Behavioral segmentation",
    "matched_text": "Behavioral segmentation",
    "vi": "Phân khúc theo hành vi"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Target market",
    "definition": "A set of buyers who share common needs or characteristics that a company decides to serve.",
    "example": "Choosing a target market means deliberately choosing who NOT to serve, too.",
    "blanked": "Choosing a [[BLANK]] means deliberately choosing who NOT to serve, too.",
    "blank_answer": "target market",
    "matched_text": "target market",
    "vi": "Thị trường mục tiêu"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Differentiation",
    "definition": "Actually differentiating the market offering to create superior customer value.",
    "example": "Differentiation is what makes a customer choose you over the competitor sitting right next to you.",
    "blanked": "[[BLANK]] is what makes a customer choose you over the competitor sitting right next to you.",
    "blank_answer": "Differentiation",
    "matched_text": "Differentiation",
    "vi": "Khác biệt hóa"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Positioning",
    "definition": "Arranging for a market offering to occupy a clear, distinctive, and desirable place relative to competing products in the minds of target consumers.",
    "example": "Good positioning means customers can finish the sentence 'this brand is the one that...' instantly.",
    "blanked": "Good [[BLANK]] means customers can finish the sentence 'this brand is the one that...' instantly.",
    "blank_answer": "positioning",
    "matched_text": "positioning",
    "vi": "Định vị"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Positioning statement",
    "definition": "A statement that summarizes company or brand positioning using this form: To (target segment and need) our (brand) is (concept) that (point of difference).",
    "example": "Try writing your own company's positioning statement in one sentence using this template.",
    "blanked": "Try writing your own company's [[BLANK]] in one sentence using this template.",
    "blank_answer": "positioning statement",
    "matched_text": "positioning statement",
    "vi": "Tuyên bố định vị"
  },
  {
    "week": 6,
    "topic": "Segmentation, Targeting & Positioning (STP)",
    "term": "Value proposition",
    "definition": "The full positioning of a brand — the full mix of benefits on which it is positioned.",
    "example": "The value proposition has to be something competitors can't easily copy.",
    "blanked": "The [[BLANK]] has to be something competitors can't easily copy.",
    "blank_answer": "value proposition",
    "matched_text": "value proposition",
    "vi": "Đề xuất giá trị"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Product line",
    "definition": "A group of products that are closely related because they function in a similar manner, are sold to the same customer groups, are marketed through the same types of outlets, or fall within given price ranges.",
    "example": "A product line isn't just 'more products' — they have to be related.",
    "blanked": "A [[BLANK]] isn't just 'more products' — they have to be related.",
    "blank_answer": "product line",
    "matched_text": "product line",
    "vi": "Dòng sản phẩm"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Product mix",
    "definition": "The set of all product lines and items that a particular seller offers for sale.",
    "example": "A company's whole product mix should still feel coherent to a customer, even with many lines.",
    "blanked": "A company's whole [[BLANK]] should still feel coherent to a customer, even with many lines.",
    "blank_answer": "product mix",
    "matched_text": "product mix",
    "vi": "Danh mục sản phẩm"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Brand equity",
    "definition": "The differential effect that knowing the brand name has on customer response to the product or its marketing.",
    "example": "Two identical products can sell differently purely because of brand equity.",
    "blanked": "Two identical products can sell differently purely because of [[BLANK]].",
    "blank_answer": "brand equity",
    "matched_text": "brand equity",
    "vi": "Tài sản thương hiệu"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Product life cycle (PLC)",
    "definition": "The course of a product's sales and profits over its lifetime.",
    "example": "Knowing where a product sits on the product life cycle changes what marketing actions make sense.",
    "blanked": "Knowing where a product sits on the [[BLANK]] changes what marketing actions make sense.",
    "blank_answer": "product life cycle",
    "matched_text": "product life cycle",
    "vi": "Vòng đời sản phẩm"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Introduction stage",
    "definition": "The PLC stage in which a new product is first distributed and made available for purchase.",
    "example": "In the introduction stage, profits are usually low or negative because of launch costs.",
    "blanked": "In the [[BLANK]], profits are usually low or negative because of launch costs.",
    "blank_answer": "introduction stage",
    "matched_text": "introduction stage",
    "vi": "Giai đoạn giới thiệu"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Growth stage",
    "definition": "The PLC stage in which a product's sales start climbing quickly.",
    "example": "During the growth stage, competitors often start copying the product.",
    "blanked": "During the [[BLANK]], competitors often start copying the product.",
    "blank_answer": "growth stage",
    "matched_text": "growth stage",
    "vi": "Giai đoạn tăng trưởng"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Maturity stage",
    "definition": "The PLC stage in which a product's sales growth slows or levels off.",
    "example": "Most products you use every day are probably in the maturity stage.",
    "blanked": "Most products you use every day are probably in the [[BLANK]].",
    "blank_answer": "maturity stage",
    "matched_text": "maturity stage",
    "vi": "Giai đoạn trưởng thành"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Decline stage",
    "definition": "The PLC stage in which a product's sales fade away.",
    "example": "Companies must decide whether to revive, harvest, or drop a product in the decline stage.",
    "blanked": "Companies must decide whether to revive, harvest, or drop a product in the [[BLANK]].",
    "blank_answer": "decline stage",
    "matched_text": "decline stage",
    "vi": "Giai đoạn suy thoái"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Cost-based pricing",
    "definition": "Setting prices based on the costs of producing, distributing, and selling the product plus a fair rate of return for effort and risk.",
    "example": "Cost-based pricing is simple, but it ignores what customers are actually willing to pay.",
    "blanked": "[[BLANK]] is simple, but it ignores what customers are actually willing to pay.",
    "blank_answer": "Cost-based pricing",
    "matched_text": "Cost-based pricing",
    "vi": "Định giá dựa trên chi phí"
  },
  {
    "week": 7,
    "topic": "Product, Brand & Pricing",
    "term": "Break-even pricing (target return pricing)",
    "definition": "Setting price to break even on the costs of making and marketing a product or setting price to make a target return.",
    "example": "Her finance chapter will likely need a break-even pricing calculation.",
    "blanked": "Her finance chapter will likely need a [[BLANK]] calculation.",
    "blank_answer": "break-even pricing",
    "matched_text": "break-even pricing",
    "vi": "Định giá hòa vốn"
  },
  {
    "week": 8,
    "topic": "Place & Distribution",
    "term": "Marketing channel",
    "definition": "(Channel level) A layer of intermediaries that performs some work in bringing the product and its ownership closer to the final buyer.",
    "example": "Every extra marketing channel level usually adds cost but also adds reach.",
    "blanked": "Every extra [[BLANK]] level usually adds cost but also adds reach.",
    "blank_answer": "marketing channel",
    "matched_text": "marketing channel",
    "vi": "Kênh marketing / kênh phân phối"
  },
  {
    "week": 8,
    "topic": "Place & Distribution",
    "term": "Supply chain management",
    "definition": "Managing upstream and downstream value-added flows of materials, final goods, and related information among suppliers, the company, resellers, and final consumers.",
    "example": "Good supply chain management keeps products on shelves without overstocking.",
    "blanked": "Good [[BLANK]] keeps products on shelves without overstocking.",
    "blank_answer": "supply chain management",
    "matched_text": "supply chain management",
    "vi": "Quản trị chuỗi cung ứng"
  },
  {
    "week": 8,
    "topic": "Place & Distribution",
    "term": "Intensive distribution",
    "definition": "Stocking the product in as many outlets as possible.",
    "example": "Snacks and soft drinks usually use intensive distribution because they're bought on impulse.",
    "blanked": "Snacks and soft drinks usually use [[BLANK]] because they're bought on impulse.",
    "blank_answer": "intensive distribution",
    "matched_text": "intensive distribution",
    "vi": "Phân phối rộng rãi"
  },
  {
    "week": 8,
    "topic": "Place & Distribution",
    "term": "Exclusive distribution",
    "definition": "Giving a limited number of dealers the exclusive right to distribute the company's products in their territories.",
    "example": "Luxury brands often choose exclusive distribution to protect their image.",
    "blanked": "Luxury brands often choose [[BLANK]] to protect their image.",
    "blank_answer": "exclusive distribution",
    "matched_text": "exclusive distribution",
    "vi": "Phân phối độc quyền"
  },
  {
    "week": 8,
    "topic": "Place & Distribution",
    "term": "Disintermediation",
    "definition": "The cutting out of marketing channel intermediaries by product or service producers or the displacement of traditional resellers by radical new types of intermediaries.",
    "example": "Selling directly to customers online instead of through a retailer is a form of disintermediation.",
    "blanked": "Selling directly to customers online instead of through a retailer is a form of [[BLANK]].",
    "blank_answer": "disintermediation",
    "matched_text": "disintermediation",
    "vi": "Loại bỏ trung gian"
  },
  {
    "week": 8,
    "topic": "Place & Distribution",
    "term": "Retailing",
    "definition": "All the activities involved in selling goods or services directly to final consumers for their personal, nonbusiness use.",
    "example": "Retailing covers everything from physical stores to e-commerce.",
    "blanked": "[[BLANK]] covers everything from physical stores to e-commerce.",
    "blank_answer": "Retailing",
    "matched_text": "Retailing",
    "vi": "Bán lẻ"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Integrated marketing communications (IMC)",
    "definition": "Carefully integrating and coordinating the company's many communications channels to deliver a clear, consistent, and compelling message about the organization and its products.",
    "example": "Without IMC, a company's ads, social media, and sales team can end up telling three different stories.",
    "blanked": "Without [[BLANK]], a company's ads, social media, and sales team can end up telling three different stories.",
    "blank_answer": "IMC",
    "matched_text": "IMC",
    "vi": "Truyền thông marketing tích hợp"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Promotion mix (marketing communications mix)",
    "definition": "The specific blend of promotion tools that the company uses to persuasively communicate customer value and build customer relationships.",
    "example": "Her 12-month action plan should specify which tools make up the promotion mix each month.",
    "blanked": "Her 12-month action plan should specify which tools make up the [[BLANK]] each month.",
    "blank_answer": "promotion mix",
    "matched_text": "promotion mix",
    "vi": "Phối thức xúc tiến"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Advertising",
    "definition": "Any paid form of nonpersonal presentation and promotion of ideas, goods, or services by an identified sponsor.",
    "example": "Advertising is paid and nonpersonal — that's what separates it from personal selling.",
    "blanked": "[[BLANK]] is paid and nonpersonal — that's what separates it from personal selling.",
    "blank_answer": "Advertising",
    "matched_text": "Advertising",
    "vi": "Quảng cáo"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Public relations (PR)",
    "definition": "Building good relations with the company's various publics by obtaining favorable publicity; building up a good corporate image; and handling or heading off unfavorable rumors, stories, and events.",
    "example": "Good PR is often invisible — you only notice it when it's missing during a crisis.",
    "blanked": "Good [[BLANK]] is often invisible — you only notice it when it's missing during a crisis.",
    "blank_answer": "PR",
    "matched_text": "PR",
    "vi": "Quan hệ công chúng"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Personal selling",
    "definition": "Personal presentation by the firm's sales force for the purpose of engaging customers, making sales, and building customer relationships.",
    "example": "Personal selling matters most for expensive or complex products that need explanation.",
    "blanked": "[[BLANK]] matters most for expensive or complex products that need explanation.",
    "blank_answer": "Personal selling",
    "matched_text": "Personal selling",
    "vi": "Bán hàng cá nhân"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Sales promotion",
    "definition": "Short-term incentives to encourage the purchase or sale of a product or service.",
    "example": "A limited-time discount is a classic sales promotion, not a long-term pricing strategy.",
    "blanked": "A limited-time discount is a classic [[BLANK]], not a long-term pricing strategy.",
    "blank_answer": "sales promotion",
    "matched_text": "sales promotion",
    "vi": "Khuyến mại"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Push strategy",
    "definition": "A promotion strategy that calls for using the sales force and trade promotion to push the product through channels.",
    "example": "A push strategy convinces retailers to stock and promote the product for you.",
    "blanked": "A [[BLANK]] convinces retailers to stock and promote the product for you.",
    "blank_answer": "push strategy",
    "matched_text": "push strategy",
    "vi": "Chiến lược đẩy"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Pull strategy",
    "definition": "A promotion strategy that calls for spending a lot on consumer advertising and promotion to induce final consumers to buy the product, creating a demand vacuum that 'pulls' the product through the channel.",
    "example": "A pull strategy works when customers walk into a store already asking for your brand by name.",
    "blanked": "A [[BLANK]] works when customers walk into a store already asking for your brand by name.",
    "blank_answer": "pull strategy",
    "matched_text": "pull strategy",
    "vi": "Chiến lược kéo"
  },
  {
    "week": 9,
    "topic": "Promotion & Integrated Marketing Communications",
    "term": "Digital and social media marketing",
    "definition": "Using digital marketing tools such as websites, social media, mobile apps and ads, online video, and other digital platforms to engage consumers anywhere, at any time, via their digital devices.",
    "example": "For most new brands today, digital and social media marketing is the cheapest way to reach a target segment.",
    "blanked": "For most new brands today, [[BLANK]] is the cheapest way to reach a target segment.",
    "blank_answer": "digital and social media marketing",
    "matched_text": "digital and social media marketing",
    "vi": "Marketing số và mạng xã hội"
  },
  {
    "week": 10,
    "topic": "Competitive Strategy & The Marketing Plan",
    "term": "Competitive advantage",
    "definition": "An advantage over competitors gained by offering greater customer value either by having lower prices or providing more benefits that justify higher prices.",
    "example": "A real competitive advantage is hard for rivals to copy quickly.",
    "blanked": "A real [[BLANK]] is hard for rivals to copy quickly.",
    "blank_answer": "competitive advantage",
    "matched_text": "competitive advantage",
    "vi": "Lợi thế cạnh tranh"
  },
  {
    "week": 10,
    "topic": "Competitive Strategy & The Marketing Plan",
    "term": "Market leader",
    "definition": "The firm in an industry with the largest market share.",
    "example": "The market leader usually has the most to lose from a price war.",
    "blanked": "The [[BLANK]] usually has the most to lose from a price war.",
    "blank_answer": "market leader",
    "matched_text": "market leader",
    "vi": "Dẫn đầu thị trường"
  },
  {
    "week": 10,
    "topic": "Competitive Strategy & The Marketing Plan",
    "term": "Market challenger",
    "definition": "A runner-up firm that is fighting hard to increase its market share in an industry.",
    "example": "A market challenger often attacks the leader's weakest point directly.",
    "blanked": "A [[BLANK]] often attacks the leader's weakest point directly.",
    "blank_answer": "market challenger",
    "matched_text": "market challenger",
    "vi": "Thách thức thị trường"
  },
  {
    "week": 10,
    "topic": "Competitive Strategy & The Marketing Plan",
    "term": "Market follower",
    "definition": "A runner-up firm that wants to hold its share in an industry without rocking the boat.",
    "example": "A market follower copies what works instead of innovating first.",
    "blanked": "A [[BLANK]] copies what works instead of innovating first.",
    "blank_answer": "market follower",
    "matched_text": "market follower",
    "vi": "Theo sau thị trường"
  },
  {
    "week": 10,
    "topic": "Competitive Strategy & The Marketing Plan",
    "term": "Market nicher",
    "definition": "A firm that serves small segments that the other firms in an industry overlook or ignore.",
    "example": "A market nicher survives by being too small and specific for the big players to bother with.",
    "blanked": "A [[BLANK]] survives by being too small and specific for the big players to bother with.",
    "blank_answer": "market nicher",
    "matched_text": "market nicher",
    "vi": "Chuyên gia thị trường ngách"
  },
  {
    "week": 10,
    "topic": "Competitive Strategy & The Marketing Plan",
    "term": "Competitor analysis",
    "definition": "Identifying key competitors; assessing their objectives, strategies, strengths and weaknesses, and reaction patterns; and selecting which competitors to attack or avoid.",
    "example": "A thorough competitor analysis should end with a clear recommendation, not just a list of rivals.",
    "blanked": "A thorough [[BLANK]] should end with a clear recommendation, not just a list of rivals.",
    "blank_answer": "competitor analysis",
    "matched_text": "competitor analysis",
    "vi": "Phân tích đối thủ cạnh tranh"
  },
  {
    "week": 10,
    "topic": "Competitive Strategy & The Marketing Plan",
    "term": "Marketing return on investment (marketing ROI)",
    "definition": "The net return from a marketing investment divided by the costs of the marketing investment.",
    "example": "Investors will ask about marketing ROI before approving her 12-month plan's budget.",
    "blanked": "Investors will ask about [[BLANK]] before approving her 12-month plan's budget.",
    "blank_answer": "marketing ROI",
    "matched_text": "marketing ROI",
    "vi": "Tỷ suất hoàn vốn marketing"
  }
];
